### ISSUE TITLE
Do Not Expose sensitive information to browser

### ISSUE THREAD

**Issue by mishraomp** [bcgov/nr-epd-digital-services#206]
**Describe the task**
Currently sensitive information like client_secret et.. are exposed to broswer, changes needs to be made to make sure sensitive information like credentials are not send over to browser.

**Comment by nikhila-aot** [comment]
Yes @mishraomp - aware of this issue, We had to make changes in Openshift so that the web app picks up env values from config map config.js. The web app was not taking the values when we tried setting it up directly as key value pair in config map or secrets. This change introduced this issue. We will be sorting it out.

**Comment by nikhila-aot** [comment]
secret is now removed from the browser

**Comment by mishraomp** [comment]
nicely done :)
